env:
  - R_HOME=/usr/lib/R
rvm:
  - 2.0.0
gemfile:
  - Gemfile
branches:
  only:
    - master
before_install:
 - sudo apt-add-repository -y ppa:marutter/rdev
 - sudo apt-get update -qq
 - sudo apt-get install -qq r-base-dev
 - bundle config build.rsruby --with-R-include=/usr/share/R/include
